version: '3'
services:
  nginx:
    build: .
    container_name: "website"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/denis/volumes/website/data/certbot/conf:/etc/letsencrypt
      - /home/denis/volumes/website/data/certbot/www:/var/www/certbot
  certbot:
    image: certbot/certbot
    container_name: "certbot"
    volumes:
      - /home/denis/volumes/website/data/certbot/conf:/etc/letsencrypt
      - /home/denis/volumes/website/data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"